//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadatakA16_IzlozbaPasa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class A16Entities3 : DbContext
    {
        public A16Entities3()
            : base("name=A16Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boja> Bojas { get; set; }
        public virtual DbSet<Duzina_Dlake> Duzina_Dlake { get; set; }
        public virtual DbSet<Izlozba> Izlozbas { get; set; }
        public virtual DbSet<Kategorija> Kategorijas { get; set; }
        public virtual DbSet<Odgajivac> Odgajivacs { get; set; }
        public virtual DbSet<Pa> Pas { get; set; }
        public virtual DbSet<Pol> Pols { get; set; }
        public virtual DbSet<Rasa> Rasas { get; set; }
        public virtual DbSet<Rezultat> Rezultats { get; set; }
        public virtual DbSet<Vlasnik> Vlasniks { get; set; }
    }
}
