//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadatakA16_IzlozbaPasa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odgajivac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odgajivac()
        {
            this.Pas = new HashSet<Pa>();
        }
    
        public int OdgajivacId { get; set; }
        public string ime { get; set; }
        public string broj_telefona { get; set; }
        public string email { get; set; }
        public string adresa { get; set; }
        public string drzava { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pa> Pas { get; set; }
    }
}
